### ISSUE TITLE
Dockerize system

### ISSUE THREAD

**Issue by WilliamMRS** [CogitoNTNU/jarvis#4]
To improve the deployment process and ensure consistency across different environments, we need to dockerize key components of our system. This includes creating Docker services for the vector database, the frontend, and the backend applications.

**Acceptence criteria**:
- [x] Add docker service for developer environment
- [ ] docker file for  speech
- [x] docker file for core

**Comment by SverreNystad** [comment]
The current docker image makes it possible to have the same development environment on all machines. How to use this is also documented in the docs/manuals/developer_setup.md
